### ISSUE TITLE
can not change tinymce value when i change v-model

### ISSUE THREAD

**Issue by minikiller** [PanJiaChen/vue-element-admin#411] opened 2018-01-18 16:28 UTC
i add a button to example vue page. when clicked it changed v-model value,but i found it can not change tinymce value.

thanks for your help!

**Comment by PanJiaChen** [comment] 2018-01-19 02:51
Duplicate of #251 
Detail see [Document](https://panjiachen.github.io/vue-element-admin-site/#/rich-editor?id=tinymce)

**Closed by PanJiaChen** 2018-01-19 02:51 UTC
